// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiniProjects.Models
{
    public partial class Product
    {
        public Guid Id { get; set; }
        public string ProductsName { get; set; }
        public decimal ProductsPrices { get; set; }
        public int Quantity { get; set; }
    }
}