// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFrontEnd.Models
{
    public partial class YearlyReport
    {
        public string ProductsName { get; set; }
        public decimal? TotalYearly { get; set; }
    }
}