// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrxServices.Models
{
    public partial class DailyReport
    {
        public string ProductsName { get; set; }
        public decimal? TotalDaily { get; set; }
    }
}