// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrxServices.Models
{
    public partial class DetailTransaction
    {
        public Guid Id { get; set; }
        public Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPerTrx { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ProductsName { get; set; }
    }
}