// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrxServices.Models
{
    public partial class Reporting
    {
        public Guid Id { get; set; }
        public Guid? TransactionId { get; set; }
        public decimal TotalPayment { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}